### ISSUE TITLE
Incorrect highliting for $__ 

### ISSUE THREAD

**Issue by bucaran** [davidcelis/language-fish-shell#4]
<img width="166" alt="screen shot 2016-01-22 at 2 54 04 pm" src="https://cloud.githubusercontent.com/assets/8317250/12503491/08960cda-c118-11e5-8f53-934b2ab96370.png">

In this case, `$_` is part of the name of the variable `$__why` and has nothing to do with `$_`.

**Comment by davidcelis** [comment]
Agh, that's annoying! Sorry about that! To reiterate what I said in another issue (#1), this is basically just a port of a TextMate theme for personal use and I never took the time to learn the nuances of how the syntax works because it worked well enough for me. I know that's probably a frustrating answer, but I would be willing to work with someone collaboratively on getting these issues fixed or even accepting blind pull requests!

**Comment by bucaran** [comment]
:+1: Roger that.

**Comment by RSully** [comment]
@davidcelis can you confirm if this is based off of @l15n's tmbundle? I'd like to report these issues upstream then.

**Comment by davidcelis** [comment]
@RSully It is indeed!

**Comment by nomaed** [comment]
So I guess that this issue is fixed by https://github.com/davidcelis/language-fish-shell/pull/9
I don't know how to associate a pull request with an issue though...

**Comment by davidcelis** [comment]
@nomaed I can close it out from here 😄 For future reference, GitHub [detects things like "Closes #4" or "Fixes #4" and will close out the associated issue automatically](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by nomaed** [comment]
Every day, something new ;)
